### ISSUE TITLE
listen_for_dweets_from throws exceptions every minute

### ISSUE THREAD

**Issue by viljamip** [paddycarey/dweepy#14]
For some reason I get an ConnectionError if nothing is happening in the stream for a while. I can catch that exception and run the listen_for_dweets_from() again but I get exceptions almost exactly every 60 seconds. Do you have any idea what might cause this? If I use a thing that sends data more often the stream stays alive. My dweet.io thing sends data only occasionally so there might be hours between events. 

Here is my test code:
```
import dweepy
import datetime
import sys

while(True):
	try:
		for dweet in dweepy.listen_for_dweets_from('ViljaminAlyvalot'):
			print(dweet)
	except KeyboardInterrupt:
		sys.exit(0)
	except:
		print("Exception:", sys.exc_info()[0], datetime.datetime.now())

```

Which produces:
```
Exception: <class 'requests.exceptions.ConnectionError'> 2019-03-02 17:04:07.480988
Exception: <class 'requests.exceptions.ConnectionError'> 2019-03-02 17:05:07.484771
Exception: <class 'requests.exceptions.ConnectionError'> 2019-03-02 17:06:06.988063
Exception: <class 'requests.exceptions.ConnectionError'> 2019-03-02 17:07:06.988028
```

Here is the full traceback. Usually I only see the last one (requests.exceptions.ConnectionError) but sometimes all of these are shown:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dweepyTest.py", line 3, in <module>
    for dweet in dweepy.listen_for_dweets_from('ViljaminAlyvalot'):
  File "/usr/local/lib/python3.6/site-packages/dweepy/streaming.py", line 70, in listen_for_dweets_from
    resp = session.send(request, stream=True, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by sergimn** [comment]
No expert here but seems like dweet.io is closing the connection from their side. You are not the only one with this issue. 
I thought the _listen/for/dweets_ was designed to provide an easy  way to check for changes but it seems like it's easier to just poll the thing every 5 seconds

**Comment by viljamip** [comment]
Yes, that is probably what is happening. I ended up just catching the exception and restarting the connection whenever it drops. Polling would probably be smarter though.

**Comment by sergimn** [comment]
Maybe you could do a _pull request_ to implement this feature into this code? That would be super nice. Or maybe share the code you wrote.
I'm just lazy and I don't want to do it myself :c

**Comment by Zylvian** [comment]
I'm also having this problem, is this expected of dweet? What's the reason for subscribing to the feed if you end up being yoinked every minute?

I ended up with this recursive travesty:

```
def cycle_from_dweet()
        try:
            for dweet in dweepy.listen_for_dweets_from('omelette250'):
                # code stuff...
                # ...
                print("Listening to updates from dweet thing 'omelette250'...")

        except requests.exceptions.ConnectionError as e:
            print(e.response)
            print("Connection closed by dweet, restarting:")
            cycle_from_dweet()

```

**Comment by sergimn** [comment]
What I did to solve this issue in a clean way so I don't overload my system or dweet's system is just using a keepalive that I send through my system. The following is a simplification of my code:
```python
import time
import dweepy
from multiprocessing import pool

def main():
    p = pool.Pool()
    p.apply_async(keepalive, args=[dweet_id])
    manage(dweet_id)

def keepalive(id):
    while True:
        time.sleep(45)
        dweepy.dweet_for(thing_name=id,payload={"keepalive": 1}) # This is prone to failure so you have to implement a retry mechanism, but it should work 99.9% of the time 

def manage(id):
    dweepy.dweet_for(thing_name=id, payload={})
    for dweet in dweepy.listen_for_dweets_from(id):
        cnt = dweet['content']
        if "keepalive" in cnt:
            pass

        if cnt.setdefault(property1):
            pass
        if cnt.setdefault(property2):
            pass
```
